
package wsdlservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CCMovelDigitalSignature", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://cmd.autenticacao.gov.pt/Ama.Authentication.Frontend/CCMovelDigitalSignature.svc?wsdl")
public class CCMovelDigitalSignature
    extends Service
{

    private final static URL CCMOVELDIGITALSIGNATURE_WSDL_LOCATION;
    private final static WebServiceException CCMOVELDIGITALSIGNATURE_EXCEPTION;
    private final static QName CCMOVELDIGITALSIGNATURE_QNAME = new QName("http://tempuri.org/", "CCMovelDigitalSignature");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cmd.autenticacao.gov.pt/Ama.Authentication.Frontend/CCMovelDigitalSignature.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CCMOVELDIGITALSIGNATURE_WSDL_LOCATION = url;
        CCMOVELDIGITALSIGNATURE_EXCEPTION = e;
    }

    public CCMovelDigitalSignature() {
        super(__getWsdlLocation(), CCMOVELDIGITALSIGNATURE_QNAME);
    }

    public CCMovelDigitalSignature(WebServiceFeature... features) {
        super(__getWsdlLocation(), CCMOVELDIGITALSIGNATURE_QNAME, features);
    }

    public CCMovelDigitalSignature(URL wsdlLocation) {
        super(wsdlLocation, CCMOVELDIGITALSIGNATURE_QNAME);
    }

    public CCMovelDigitalSignature(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CCMOVELDIGITALSIGNATURE_QNAME, features);
    }

    public CCMovelDigitalSignature(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCMovelDigitalSignature(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CCMovelSignature
     */
    @WebEndpoint(name = "BasicHttpBinding_CCMovelSignature")
    public CCMovelSignature getBasicHttpBindingCCMovelSignature() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_CCMovelSignature"), CCMovelSignature.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CCMovelSignature
     */
    @WebEndpoint(name = "BasicHttpBinding_CCMovelSignature")
    public CCMovelSignature getBasicHttpBindingCCMovelSignature(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_CCMovelSignature"), CCMovelSignature.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CCMOVELDIGITALSIGNATURE_EXCEPTION!= null) {
            throw CCMOVELDIGITALSIGNATURE_EXCEPTION;
        }
        return CCMOVELDIGITALSIGNATURE_WSDL_LOCATION;
    }

}
